------------------------------------------------------------------------
-- 1. 거래 로그 관리 
------------------------------------------------------------------------

CREATE TABLE GSI.TB_TRNSCTN_LOG
(
	IDX				NUMBER			NOT NULL,
	MERCHANT_ID			VARCHAR2(20 BYTE)   	NOT NULL,
	SERVICE_TYPE			VARCHAR2(8 BYTE)	NOT NULL,
	TRANSACTION_ID			VARCHAR2(12 BYTE)	,
	IPADDRESS			VARCHAR2(30 BYTE)	NOT NULL,
	REQ_DATA			VARCHAR2(600 BYTE)	,
	RES_DATA			VARCHAR2(600 BYTE)	,
	STATUS				VARCHAR2(2 BYTE)	DEFAULT '11' NOT NULL,
	REG_DATE			DATE			DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_TRNSCTN_LOG" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE GSI.TB_TRNSCTN_LOG				IS '거래 로그 관리';
COMMENT ON COLUMN GSI.TB_TRNSCTN_LOG.IDX			IS '인덱스';
COMMENT ON COLUMN GSI.TB_TRNSCTN_LOG.MERCHANT_ID		IS 'MERCHANT ID';
COMMENT ON COLUMN GSI.TB_TRNSCTN_LOG.SERVICE_TYPE		IS 'TERMINAL,MOBILE,WEB';
COMMENT ON COLUMN GSI.TB_TRNSCTN_LOG.TRANSACTION_ID		IS 'PWN 거래 번호 ';
COMMENT ON COLUMN GSI.TB_TRNSCTN_LOG.IPADDRESS			IS '접속 아이피 주소 또는 어플리케이션 이름 ';
COMMENT ON COLUMN GSI.TB_TRNSCTN_LOG.REQ_DATA			IS '요청 데이터';
COMMENT ON COLUMN GSI.TB_TRNSCTN_LOG.RES_DATA			IS '응답 데이터';
COMMENT ON COLUMN GSI.TB_TRNSCTN_LOG.STATUS			IS '상태 11:요청,99:실패,00:성공';
COMMENT ON COLUMN GSI.TB_TRNSCTN_LOG.REG_DATE			IS '등록일';


CREATE SEQUENCE  "GSI"."SEQ_TRNSCTN_LOG"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_TRNSCTN_LOG AS
SELECT IDX,MERCHANT_ID,SERVICE_TYPE,TRANSACTION_ID,IPADDRESS,REQ_DATA,RES_DATA,STATUS,REG_DATE
FROM GSI.TB_TRNSCTN_LOG;


------------------------------------------------------------------------
-- 2. PG 거래번호 생성  
------------------------------------------------------------------------
CREATE TABLE GSI.TB_SEQUENCE
(
	IDX				INTEGER			,
	SEQ_DAY				CHAR(8 BYTE)   		,
	SEQUENCE			NUMBER 			,
	SEQ_TYPE			VARCHAR2(20 BYTE)	,
	CONSTRAINT "TB_SEQUENCE" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE GSI.TB_SEQUENCE				IS 'PWN PG웹결제 HTTP 결과 전달 정보 관리 ';
COMMENT ON COLUMN GSI.TB_SEQUENCE.IDX			IS '인덱스';
COMMENT ON COLUMN GSI.TB_SEQUENCE.SEQ_DAY		IS '시퀀스 날짜';
COMMENT ON COLUMN GSI.TB_SEQUENCE.SEQUENCE		IS '시퀀스번호';
COMMENT ON COLUMN GSI.TB_SEQUENCE.SEQ_TYPE		IS '시퀀스 이름 ';

CREATE SEQUENCE  "GSI"."SEQ_SEQUENCE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_SEQUENCE AS
SELECT IDX,SEQ_DAY,SEQUENCE,SEQ_TYPE
FROM GSI.TB_SEQUENCE;


CREATE OR REPLACE PROCEDURE GSI.GET_SEQ
(
 v_str IN varchar,
 getseqval OUT varchar
)
IS

v_sday varchar(10);
today varchar(10);
v_seq varchar(10);
v_str_count number;

BEGIN

   
   SELECT count(*) into v_str_count FROM VW_SEQUENCE where SEQ_TYPE = v_str;
   
   select to_char(sysdate,'YYYYMMDD') into today from dual;

   
   IF  v_str_count = 0  THEN            
    insert into TB_SEQUENCE (IDX,SEQ_DAY,SEQUENCE,SEQ_TYPE) values (SEQ_SEQUENCE.NEXTVAL,today,1,v_str);
    commit;    
   END IF;
   
   
   SELECT SEQ_DAY into v_sday  FROM VW_SEQUENCE where SEQ_TYPE = v_str;
 
    
   IF  v_sday  != today  THEN    
     UPDATE TB_SEQUENCE SET SEQ_DAY = today, SEQUENCE = 1 where SEQ_TYPE = v_str;
     commit;
     SELECT SEQ_DAY into v_sday  FROM VW_SEQUENCE where SEQ_TYPE = v_str;
     SELECT max(SEQUENCE) into v_seq from VW_SEQUENCE where SEQ_TYPE = v_str;
   END IF;
                   
   IF  v_sday = today  THEN    
     SELECT SEQ_DAY into v_sday  FROM VW_SEQUENCE where SEQ_TYPE = v_str;
     SELECT max(SEQUENCE) into v_seq from VW_SEQUENCE where SEQ_TYPE = v_str;
   END IF;
   
   
   
   UPDATE TB_SEQUENCE SET SEQUENCE = SEQUENCE + 1 where SEQ_TYPE = v_str;    
   commit;
   
   
   getseqval := to_char(sysdate,'YYMMDD')||lpad(to_char(v_seq),'6','0');

END GET_SEQ;
/


------------------------------------------------------------------------
-- 3. NOTICE 관리 
------------------------------------------------------------------------

CREATE TABLE GSI.TB_NOTICE
(
	IDX				NUMBER				NOT NULL,
	MEMBER_NAME			VARCHAR2(20 BYTE)		NOT NULL,
	SUBJECT				VARCHAR2(1000 BYTE)		NOT NULL,
	CONTENTS			CLOB				,
	ACTIVE				CHAR(1 BYTE)		DEFAULT 'Y'	NOT NULL,
	REG_DATE			DATE				DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_NOTICE" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE GSI.TB_NOTICE					IS 'PWN PG 고객관리';
COMMENT ON COLUMN GSI.TB_NOTICE.IDX				IS '인덱스';
COMMENT ON COLUMN GSI.TB_NOTICE.MEMBER_NAME			IS '작성자이름';
COMMENT ON COLUMN GSI.TB_NOTICE.SUBJECT				IS '제목';
COMMENT ON COLUMN GSI.TB_NOTICE.CONTENTS			IS '내용';
COMMENT ON COLUMN GSI.TB_NOTICE.ACTIVE				IS '문서보기여부 Y:참,N:거짓';
COMMENT ON COLUMN GSI.TB_NOTICE.REG_DATE			IS '문서등록일';


CREATE SEQUENCE  "GSI"."SEQ_NOTICE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;


CREATE VIEW VW_NOTICE AS
SELECT IDX,MEMBER_NAME,SUBJECT,CONTENTS,ACTIVE,REG_DATE
  FROM GSI.TB_NOTICE ;

------------------------------------------------------------------------
-- 4. 가맹점 질문 내용
------------------------------------------------------------------------

CREATE TABLE GSI.TB_QUESTION
(
	IDX				NUMBER				NOT NULL,
	MERCHANT_ID			VARCHAR2(20 BYTE)		NOT NULL,
	MEMBER_NAME			VARCHAR2(400 BYTE)		NOT NULL,
	SUBJECT				VARCHAR2(1000 BYTE)		NOT NULL,
	EMAIL				VARCHAR2(100 BYTE)		NOT NULL,
	CONTENTS			CLOB				,
	ACTIVE				CHAR(1 BYTE)			DEFAULT 'Y'		NOT NULL,
	REG_DATE			DATE				DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_QUESTION" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE GSI.TB_QUESTION			IS 'PWN PG 고객관리';
COMMENT ON COLUMN GSI.TB_QUESTION.IDX			IS '인덱스';
COMMENT ON COLUMN GSI.TB_QUESTION.MERCHANT_ID		IS '가맹점 아이디';
COMMENT ON COLUMN GSI.TB_QUESTION.MEMBER_NAME		IS '작성자이름';
COMMENT ON COLUMN GSI.TB_QUESTION.SUBJECT		IS '제목';
COMMENT ON COLUMN GSI.TB_QUESTION.EMAIL			IS '제목';
COMMENT ON COLUMN GSI.TB_QUESTION.CONTENTS		IS '내용';
COMMENT ON COLUMN GSI.TB_QUESTION.ACTIVE		IS 'Y:참,N:거짓';
COMMENT ON COLUMN GSI.TB_QUESTION.REG_DATE		IS '문서등록일';


CREATE SEQUENCE  "GSI"."SEQ_QUESTION"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;


CREATE VIEW VW_QUESTION AS
SELECT IDX,MERCHANT_ID,MEMBER_NAME,SUBJECT,EMAIL,CONTENTS,ACTIVE,REG_DATE
  FROM GSI.TB_QUESTION ;


------------------------------------------------------------------------
-- 5. PWN  접속 정보 
------------------------------------------------------------------------
 

CREATE TABLE GSI.TB_ACCESS_LOG
(
	IDX				NUMBER			NOT NULL,
	MEMBER_ID			VARCHAR2(20 BYTE)	NOT NULL,
	IPADDRESS			VARCHAR2(30 BYTE)	NOT NULL,
	USER_AGENT			VARCHAR2(200 BYTE)	,
	ACCESS_PAGE			VARCHAR2(100 BYTE)	,
	REG_DATE			DATE			DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_ACCESS_LOG" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE GSI.TB_ACCESS_LOG			IS 'PG Application Server 접속 정보';
COMMENT ON COLUMN GSI.TB_ACCESS_LOG.IDX			IS '인덱스';
COMMENT ON COLUMN GSI.TB_ACCESS_LOG.MEMBER_ID		IS 'PWN MEMBER,MERCHANT,GROUP ID';
COMMENT ON COLUMN GSI.TB_ACCESS_LOG.IPADDRESS		IS '접속 아이피 주소 또는 어플리케이션 이름 ';
COMMENT ON COLUMN GSI.TB_ACCESS_LOG.USER_AGENT		IS 'USER AGENT FIELD';
COMMENT ON COLUMN GSI.TB_ACCESS_LOG.ACCESS_PAGE		IS '접속 페이지 -URI';
COMMENT ON COLUMN GSI.TB_ACCESS_LOG.REG_DATE		IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_ACCESS_LOG"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_ACCESS_LOG AS
SELECT IDX,MEMBER_ID,IPADDRESS,USER_AGENT,ACCESS_PAGE,REG_DATE
FROM GSI.TB_ACCESS_LOG;



------------------------------------------------------------------------
-- 6. 이력 관리 - MEMBER    
------------------------------------------------------------------------
CREATE TABLE GSI.TB_COMMENT_MEMBER
(
	IDX				NUMBER				NOT NULL,
	MEMBER_ID			VARCHAR2(20 BYTE)		NOT NULL,
	COMMENTS			VARCHAR2(1000 BYTE)		NOT NULL,
	REG_DATE			DATE				DEFAULT SYSDATE	NOT NULL	
);

COMMENT ON TABLE GSI.TB_COMMENT_MEMBER				IS 'PWN PG 상점,멤버 변경  이력 관리';
COMMENT ON COLUMN GSI.TB_COMMENT_MEMBER.IDX			IS '인덱스';
COMMENT ON COLUMN GSI.TB_COMMENT_MEMBER.MEMBER_ID		IS 'PWN MEMBER ID';
COMMENT ON COLUMN GSI.TB_COMMENT_MEMBER.COMMENTS		IS '내용 ';
COMMENT ON COLUMN GSI.TB_COMMENT_MEMBER.REG_DATE		IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_COMMENT_MEMBER"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_COMMENT_MEMBER AS
SELECT IDX,MEMBER_ID,COMMENTS,REG_DATE
FROM GSI.TB_COMMENT_MEMBER;


------------------------------------------------------------------------
-- 7. 이력 관리 - SERVICE    
------------------------------------------------------------------------
CREATE TABLE GSI.TB_COMMENT_SERVICE
(
	IDX				NUMBER				NOT NULL,
	MEMBER_ID		VARCHAR2(20 BYTE)   NOT NULL,
	COMMENTS		VARCHAR2(1000 BYTE) NOT NULL,
	REG_DATE		DATE				DEFAULT SYSDATE	NOT NULL	
);

COMMENT ON TABLE GSI.TB_COMMENT_SERVICE				IS 'PWN PG 서비스 변경 이력 관리';
COMMENT ON COLUMN GSI.TB_COMMENT_SERVICE.IDX		IS '인덱스';
COMMENT ON COLUMN GSI.TB_COMMENT_SERVICE.MEMBER_ID	IS 'PWN MEMBER ID';
COMMENT ON COLUMN GSI.TB_COMMENT_SERVICE.COMMENTS	IS '내용 ';
COMMENT ON COLUMN GSI.TB_COMMENT_SERVICE.REG_DATE	IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_COMMENT_SERVICE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_COMMENT_SERVICE AS
SELECT IDX,MEMBER_ID,COMMENTS,REG_DATE
FROM GSI.TB_COMMENT_SERVICE;

------------------------------------------------------------------------
-- 8. 이력 관리 - TRNSCTN   
------------------------------------------------------------------------
CREATE TABLE GSI.TB_COMMENT_TRNSCTN
(
	IDX				NUMBER				NOT NULL,
	MEMBER_ID		VARCHAR2(20 BYTE)   NOT NULL,
	COMMENTS		VARCHAR2(1000 BYTE) NOT NULL,
	REG_DATE		DATE				DEFAULT SYSDATE	NOT NULL	
);

COMMENT ON TABLE GSI.TB_COMMENT_TRNSCTN				IS 'PWN PG 거래 변경 이력 관리';
COMMENT ON COLUMN GSI.TB_COMMENT_TRNSCTN.IDX		IS '인덱스';
COMMENT ON COLUMN GSI.TB_COMMENT_TRNSCTN.MEMBER_ID	IS 'PWN MEMBER ID';
COMMENT ON COLUMN GSI.TB_COMMENT_TRNSCTN.COMMENTS	IS '내용 ';
COMMENT ON COLUMN GSI.TB_COMMENT_TRNSCTN.REG_DATE	IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_COMMENT_TRNSCTN"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_COMMENT_TRNSCTN AS
SELECT IDX,MEMBER_ID,COMMENTS,REG_DATE
FROM GSI.TB_COMMENT_TRNSCTN;

------------------------------------------------------------------------
-- 9. 이력 관리 - SETTLE   
------------------------------------------------------------------------
CREATE TABLE GSI.TB_COMMENT_SETTLE
(
	IDX				NUMBER				NOT NULL,
	MEMBER_ID		VARCHAR2(20 BYTE)   NOT NULL,
	COMMENTS		VARCHAR2(1000 BYTE) NOT NULL,
	REG_DATE		DATE				DEFAULT SYSDATE	NOT NULL	
);

COMMENT ON TABLE GSI.TB_COMMENT_SETTLE				IS 'PWN PG 정산 이력 관리';
COMMENT ON COLUMN GSI.TB_COMMENT_SETTLE.IDX			IS '인덱스';
COMMENT ON COLUMN GSI.TB_COMMENT_SETTLE.MEMBER_ID	IS 'PWN MEMBER ID';
COMMENT ON COLUMN GSI.TB_COMMENT_SETTLE.COMMENTS		IS '내용 ';
COMMENT ON COLUMN GSI.TB_COMMENT_SETTLE.REG_DATE	IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_COMMENT_SETTLE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;


CREATE VIEW VW_COMMENT_SETTLE AS
SELECT IDX,MEMBER_ID,COMMENTS,REG_DATE
FROM GSI.TB_COMMENT_SETTLE;


------------------------------------------------------------------------
-- 10. SMS 테이블   
------------------------------------------------------------------------
CREATE TABLE TB_SMS
(
  	CMID 				VARCHAR2(32 BYTE)	NOT NULL,
  	UMID 				VARCHAR2(32 BYTE),
  	MSG_TYPE 			NUMBER(1, 0) 		NOT NULL,
  	STATUS 				NUMBER(1, 0) 		NOT NULL,
  	REQUEST_TIME 			VARCHAR2(14 BYTE) 	NOT NULL,
  	SEND_TIME 			VARCHAR2(14 BYTE),
  	REPORT_TIME 			VARCHAR2(14 BYTE),
  	DEST_PHONE 			VARCHAR2(16 BYTE) 	NOT NULL,
  	DEST_NAME 			VARCHAR2(20 BYTE),
  	SEND_PHONE 			VARCHAR2(15 BYTE),
  	SEND_NAME 			VARCHAR2(20 BYTE),
  	SUBJECT 			VARCHAR2(128 BYTE),
  	MSG_BODY 			VARCHAR2(1000 BYTE),
  	WAP_URL 			VARCHAR2(100 BYTE),
  	COVER_FLAG 			NUMBER(1, 0),
  	SMS_FLAG 			NUMBER(1, 0),
  	REPLY_FLAG 			NUMBER(1, 0),
  	RETRY_CNT 			NUMBER(1, 0),
  	FAX_FILE 			VARCHAR2(1000 BYTE),
  	VXML_FILE 			VARCHAR2(50 BYTE),
  	CALL_RESULT 			NUMBER(4, 0),
  	USE_PAGE 			NUMBER(3, 0),
  	USE_TIME 			NUMBER(3, 0),
  	SN_RESULT 			NUMBER(15, 0),
  	WAP_INFO 			VARCHAR2(10 BYTE),
  	CINFO 				VARCHAR2(32 BYTE),
  	ETC1 				VARCHAR2(50 BYTE),
  	ETC2 				VARCHAR2(50 BYTE),
  	ETC3 				VARCHAR2(50 BYTE),
  	ETC4 				VARCHAR2(50 BYTE),
  	ETC5 				VARCHAR2(50 BYTE), 
	CONSTRAINT "TB_SMS" PRIMARY KEY ("CMID")
);

CREATE SEQUENCE  "GSI"."SEQ_SMS"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;


------------------------------------------------------------------------
-- 11. SMS 테이블 로그 
------------------------------------------------------------------------
CREATE TABLE TB_SMS_LOG
(
  	CMID 				VARCHAR2(32 BYTE)	NOT NULL,
  	UMID 				VARCHAR2(32 BYTE),
  	MSG_TYPE 			NUMBER(1, 0) 		NOT NULL,
  	STATUS 				NUMBER(1, 0) 		NOT NULL,
  	REQUEST_TIME 			VARCHAR2(14 BYTE) 	NOT NULL,
  	SEND_TIME 			VARCHAR2(14 BYTE),
  	REPORT_TIME 			VARCHAR2(14 BYTE),
  	DEST_PHONE 			VARCHAR2(16 BYTE) 	NOT NULL,
  	DEST_NAME 			VARCHAR2(20 BYTE),
  	SEND_PHONE 			VARCHAR2(15 BYTE),
  	SEND_NAME 			VARCHAR2(20 BYTE),
  	SUBJECT 			VARCHAR2(128 BYTE),
  	MSG_BODY 			VARCHAR2(1000 BYTE),
  	WAP_URL 			VARCHAR2(100 BYTE),
  	COVER_FLAG 			NUMBER(1, 0),
  	SMS_FLAG 			NUMBER(1, 0),
  	REPLY_FLAG 			NUMBER(1, 0),
  	RETRY_CNT 			NUMBER(1, 0),
  	FAX_FILE 			VARCHAR2(1000 BYTE),
  	VXML_FILE 			VARCHAR2(50 BYTE),
  	CALL_RESULT 			NUMBER(4, 0),
  	USE_PAGE 			NUMBER(3, 0),
  	USE_TIME 			NUMBER(3, 0),
  	SN_RESULT 			NUMBER(15, 0),
  	WAP_INFO 			VARCHAR2(10 BYTE),
  	CINFO 				VARCHAR2(32 BYTE),
  	ETC1 				VARCHAR2(50 BYTE),
  	ETC2 				VARCHAR2(50 BYTE),
  	ETC3 				VARCHAR2(50 BYTE),
  	ETC4 				VARCHAR2(50 BYTE),
  	ETC5 				VARCHAR2(50 BYTE), 
	CONSTRAINT "TB_SMS_LOG" PRIMARY KEY ("CMID")
);


------------------------------------------------------------------------
-- 12. PG 코드 관리  
------------------------------------------------------------------------
CREATE TABLE GSI.TB_CODE
(
	IDX				NUMBER			NOT NULL,
	ALIAS				VARCHAR2(20 BYTE)	NOT NULL,
	ACODE				VARCHAR2(10 BYTE)	, 
	CODE				VARCHAR2(10 BYTE)	, 
	KR_VALUE			VARCHAR2(100 BYTE)	,				
	JP_VALUE			VARCHAR2(100 BYTE)	,
	EN_VALUE			VARCHAR2(100 BYTE)	,
	MEMBER_ID			VARCHAR2(20 BYTE)	NOT NULL,
	ACTIVE				VARCHAR2(20 BYTE)	DEFAULT 'Y' NOT NULL,
	REG_DATE			DATE			DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_CODE" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE GSI.TB_CODE				IS 'PWN PG 코드 관리 ';
COMMENT ON COLUMN GSI.TB_CODE.IDX			IS '인덱스';
COMMENT ON COLUMN GSI.TB_CODE.ALIAS			IS '별칭';
COMMENT ON COLUMN GSI.TB_CODE.ACODE			IS '코드대표값';
COMMENT ON COLUMN GSI.TB_CODE.ACODE			IS '코드값';
COMMENT ON COLUMN GSI.TB_CODE.KR_VALUE			IS '한국어 설명';
COMMENT ON COLUMN GSI.TB_CODE.JP_VALUE			IS '일본어 설명';
COMMENT ON COLUMN GSI.TB_CODE.EN_VALUE			IS '영어 설명';
COMMENT ON COLUMN GSI.TB_CODE.MEMBER_ID			IS '작성자';
COMMENT ON COLUMN GSI.TB_CODE.ACTIVE			IS '적용구분 Y,N';
COMMENT ON COLUMN GSI.TB_CODE.REG_DATE			IS '등록일';


CREATE SEQUENCE  "GSI"."SEQ_CODE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_CODE AS
SELECT IDX,ALIAS,ACODE,CODE,KR_VALUE,JP_VALUE,EN_VALUE,MEMBER_ID,ACTIVE,REG_DATE
FROM GSI.TB_CODE;

------------------------------------------------------------------------
-- 13. 거래 관리   
------------------------------------------------------------------------
CREATE TABLE GSI.TB_TRNSCTN
(
	IDX				NUMBER			NOT NULL,
	TRANSACTION_ID			VARCHAR2(12 BYTE)	NOT NULL,
	MERCHANT_ID			VARCHAR2(20 BYTE)	NOT NULL,
	MALL_ID				VARCHAR2(20 BYTE)	,
	SERVICE_TYPE			VARCHAR2(8 BYTE)	NOT NULL,
	TRN_REQ_DATE			DATE			DEFAULT SYSDATE NOT NULL,
	TRN_RES_DATE			DATE			,
	TRN_STATUS			VARCHAR2(2 BYTE)	,
	RESULT_CD			VARCHAR2(2 BYTE)	NOT NULL,
	RESULT_MSG			VARCHAR2(4 BYTE)	,
	VAN_TRANSACTION_ID		VARCHAR2(50 BYTE)	,
	APPROVAL_NO			VARCHAR2(8 BYTE)	,
	PAY_NO				VARCHAR2(50 BYTE)	,
	PAY_USERID			VARCHAR2(50 BYTE)	,
	PAY_EMAIL			VARCHAR2(100 BYTE)	,
	PAY_NAME			VARCHAR2(50 BYTE)	,
	PAY_TELNO			VARCHAR2(20 BYTE)	,
	AMOUNT				NUMBER			,
	PRODUCT_TYPE			VARCHAR2(2 BYTE)	,
	PRODUCT_NAME			VARCHAR2(50 BYTE)	,
	CUR_TYPE			CHAR(3 BYTE)		,
	IP_ADDRESS			VARCHAR2(15 BYTE)	,
	VAN				VARCHAR2(10 BYTE)	,
	TEMP1				VARCHAR2(50 BYTE)	,
	TEMP2				VARCHAR2(50 BYTE)	,
	CONSTRAINT "TB_TRNSCTN" PRIMARY KEY ("TRANSACTION_ID")
);


COMMENT ON TABLE GSI.TB_TRNSCTN					IS 'PWN PG 거래 관리 ';
COMMENT ON COLUMN GSI.TB_TRNSCTN.IDX				IS '인덱스';
COMMENT ON COLUMN GSI.TB_TRNSCTN.TRANSACTION_ID			IS 'PWN 거래번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN.MERCHANT_ID			IS '가맹점 아이디';
COMMENT ON COLUMN GSI.TB_TRNSCTN.MALL_ID			IS '아이피 주소';
COMMENT ON COLUMN GSI.TB_TRNSCTN.SERVICE_TYPE			IS '서비스유형';
COMMENT ON COLUMN GSI.TB_TRNSCTN.TRN_REQ_DATE			IS '거래요청일';
COMMENT ON COLUMN GSI.TB_TRNSCTN.TRN_RES_DATE			IS '거래응답일';
COMMENT ON COLUMN GSI.TB_TRNSCTN.TRN_STATUS			IS '거래상태(승인,매입,정산)';
COMMENT ON COLUMN GSI.TB_TRNSCTN.RESULT_CD			IS '결과코드 ';
COMMENT ON COLUMN GSI.TB_TRNSCTN.RESULT_MSG			IS '사유코드';
COMMENT ON COLUMN GSI.TB_TRNSCTN.VAN_TRANSACTION_ID		IS 'VAN 거래번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN.APPROVAL_NO			IS '승인번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN.PAY_NO				IS '가맹점주문번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN.PAY_USERID			IS '가맹점회원아이디';
COMMENT ON COLUMN GSI.TB_TRNSCTN.PAY_EMAIL			IS '가맹점회원이메일';
COMMENT ON COLUMN GSI.TB_TRNSCTN.PAY_NAME			IS '가맹점회원이름';
COMMENT ON COLUMN GSI.TB_TRNSCTN.PAY_TELNO			IS '가맹점회원전화번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN.AMOUNT				IS '금액(USD,JPY)';
COMMENT ON COLUMN GSI.TB_TRNSCTN.PRODUCT_TYPE			IS '상품구분 0:실물,1:컨텐츠';
COMMENT ON COLUMN GSI.TB_TRNSCTN.PRODUCT_NAME			IS '상품이름';
COMMENT ON COLUMN GSI.TB_TRNSCTN.CUR_TYPE			IS '거래 통화구분';
COMMENT ON COLUMN GSI.TB_TRNSCTN.IP_ADDRESS			IS 'IP 주소';
COMMENT ON COLUMN GSI.TB_TRNSCTN.VAN				IS '사용 VAN 사';
COMMENT ON COLUMN GSI.TB_TRNSCTN.TEMP1				IS '';
COMMENT ON COLUMN GSI.TB_TRNSCTN.TEMP2				IS '';


CREATE SEQUENCE  "GSI"."SEQ_TRNSCTN"  MINVALUE 0 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_TRNSCTN AS
SELECT IDX,TRANSACTION_ID,MERCHANT_ID,MALL_ID,SERVICE_TYPE,TRN_REQ_DATE	,TRN_RES_DATE,TRN_STATUS,RESULT_CD,RESULT_MSG,VAN_TRANSACTION_ID,APPROVAL_NO,PAY_NO,PAY_USERID,PAY_EMAIL,PAY_NAME,PAY_TELNO,AMOUNT,PRODUCT_TYPE,PRODUCT_NAME,CUR_TYPE,IP_ADDRESS,VAN,TEMP1,TEMP2 FROM GSI.TB_TRNSCTN;


------------------------------------------------------------------------
-- 14. PG 카드 번호 관리
------------------------------------------------------------------------
CREATE TABLE GSI.TB_TRNSCTN_SCR
(
	TRANSACTION_ID			VARCHAR2(12 BYTE)	NOT NULL,
	TRX_TYPE			VARCHAR2(4 BYTE)	, 
	CARD_TYPE			VARCHAR2(10 BYTE)	,				
	CARD_BIN			VARCHAR2(6 BYTE)	,
	CARD_NUM			VARCHAR2(50 BYTE)	,
	CARD_EXPIRE			VARCHAR2(50 BYTE)	,
	CARD_PW				VARCHAR2(50 BYTE)	,
	CARD_CVV			VARCHAR2(50 BYTE)	,
	CARD_IDENTI			VARCHAR2(50 BYTE)	,
	REG_DATE			DATE			DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_TRNSCTN_SCR" PRIMARY KEY ("TRANSACTION_ID")
);

COMMENT ON TABLE GSI.TB_TRNSCTN_SCR				IS 'PWN PG 카드번호관리 ';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.TRANSACTION_ID		IS 'PWN 거래번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.TRX_TYPE			IS '카드채번유형';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.CARD_TYPE			IS '카드발급사';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.CARD_BIN			IS '카드번호 앞 6자리';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.CARD_NUM			IS '카드번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.CARD_EXPIRE		IS '유효기간';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.CARD_PW			IS '패스워드';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.CARD_CVV			IS 'CVV';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.CARD_IDENTI		IS '식별값';
COMMENT ON COLUMN GSI.TB_TRNSCTN_SCR.REG_DATE			IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_TRNSCTN_SCR"  MINVALUE 0 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_TRNSCTN_SCR AS
SELECT TRANSACTION_ID,TRX_TYPE,CARD_TYPE,CARD_BIN,CARD_NUM,CARD_EXPIRE,CARD_PW,CARD_CVV,CARD_IDENTI,REG_DATE
FROM GSI.TB_TRNSCTN_SCR;


------------------------------------------------------------------------
-- 15. 거래취소데이터 
------------------------------------------------------------------------
CREATE TABLE GSI.TB_TRNSCTN_VOID
(
	IDX					NUMBER			NOT NULL,
	TRANSACTION_ID				VARCHAR2(12 BYTE)	NOT NULL,
	VOID_TRANSACTION_ID			VARCHAR2(12 BYTE)	NOT NULL, 
	VOID_VAN_TRANSACTION_ID			VARCHAR2(24 BYTE)	,				
	VOID_AMOUNT				NUMBER			,
	VOID_APPROVAL_NO			VARCHAR2(8 BYTE)	,
	ROOT_TRN_STATUS				VARCHAR2(6 BYTE)	,
	STATUS					VARCHAR2(2 BYTE)	DEFAULT '11' 	NOT NULL,
	VOID_RESULT_CD				VARCHAR2(6 BYTE)	,
	COMMENT_IDX				NUMBER			,
	VOID_REQ_DATE				DATE			DEFAULT SYSDATE	NOT NULL,
	VOID_RES_DATE				DATE			,
	REG_DATE						DATE	,
	CONSTRAINT "TB_TRNSCTN_VOID" PRIMARY KEY ("TRANSACTION_ID")
);

COMMENT ON TABLE GSI.TB_TRNSCTN_VOID					IS 'PWN PG 거래취소관리 ';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.TRANSACTION_ID			IS 'PWN 원거래번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.VOID_TRANSACTION_ID		IS '취소요청거래번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.VOID_VAN_TRANSACTION_ID		IS '취소VAN 거래번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.VOID_AMOUNT			IS '취소요청금액';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.VOID_APPROVAL_NO			IS '취소승인번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.ROOT_TRN_STATUS			IS '원거래 TRN_STATUS';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.STATUS				IS '처리현황(11:요청,33:중,00:성공,99:실패)';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.VOID_RESULT_CD			IS '취소처리코드';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.COMMENT_IDX			IS '코멘트번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.VOID_REQ_DATE			IS '취소요청일';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.VOID_RES_DATE			IS '취소응답일';
COMMENT ON COLUMN GSI.TB_TRNSCTN_VOID.REG_DATE				IS '등록일';


CREATE SEQUENCE  "GSI"."SEQ_TRNSCTN_VOID"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_TRNSCTN_VOID AS
SELECT IDX,TRANSACTION_ID,VOID_TRANSACTION_ID,VOID_VAN_TRANSACTION_ID,VOID_AMOUNT,VOID_APPROVAL_NO,ROOT_TRN_STATUS,STATUS,VOID_RESULT_CD,COMMENT_IDX,VOID_REQ_DATE,VOID_RES_DATE,REG_DATE
FROM GSI.TB_TRNSCTN_VOID;

------------------------------------------------------------------------
-- 16. 거래매입결과 
------------------------------------------------------------------------
CREATE TABLE GSI.TB_TRNSCTN_ACQUIRE
(
	IDX					NUMBER			NOT NULL,
	TRANSACTION_ID				VARCHAR2(12 BYTE)	NOT NULL,
	STATUS					VARCHAR2(2 BYTE)	NOT NULL, 
	ACQUIRE_DATE				VARCHAR2(8 BYTE)	,
	AMOUNT					NUMBER			,
	CARD_ERROR_CD				VARCHAR2(4 BYTE)	,
	VAN_ERROR_CD				VARCHAR2(4 BYTE)	,
	TEMP					VARCHAR2(100 BYTE)	,
	VAN					VARCHAR2(10 BYTE)	NOT NULL,
	REG_DATE				DATE			DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_TRNSCTN_ACQUIRE" PRIMARY KEY ("IDX")
					
);

COMMENT ON TABLE GSI.TB_TRNSCTN_ACQUIRE					IS 'PWN PG 매입결과 ';
COMMENT ON COLUMN GSI.TB_TRNSCTN_ACQUIRE.TRANSACTION_ID			IS 'PWN 거래번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN_ACQUIRE.STATUS				IS '매입상태코드 (00:매입완료,11:매입실패,22:매입반송,33:재매입,44:차지백등.';
COMMENT ON COLUMN GSI.TB_TRNSCTN_ACQUIRE.ACQUIRE_DATE			IS '등록일';
COMMENT ON COLUMN GSI.TB_TRNSCTN_ACQUIRE.AMOUNT				IS '매입금액';
COMMENT ON COLUMN GSI.TB_TRNSCTN_ACQUIRE.CARD_ERROR_CD			IS '카드사에러코드';
COMMENT ON COLUMN GSI.TB_TRNSCTN_ACQUIRE.VAN_ERROR_CD			IS 'VAN사 에러코드';
COMMENT ON COLUMN GSI.TB_TRNSCTN_ACQUIRE.TEMP				IS '기타정보';
COMMENT ON COLUMN GSI.TB_TRNSCTN_ACQUIRE.VAN				IS '기타정보';
COMMENT ON COLUMN GSI.TB_TRNSCTN_ACQUIRE.REG_DATE			IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_TRNSCTN_ACQUIRE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_TRNSCTN_ACQUIRE AS
SELECT IDX,TRANSACTION_ID,STATUS,ACQUIRE_DATE,AMOUNT,CARD_ERROR_CD,VAN_ERROR_CD,TEMP,VAN,REG_DATE
FROM GSI.TB_TRNSCTN_ACQUIRE;



------------------------------------------------------------------------
-- 17. 관리자 회원 
------------------------------------------------------------------------
CREATE TABLE GSI.TB_MEMBER
(
	IDX					NUMBER  		NOT NULL,
	MEMBER_ID				VARCHAR2(12 BYTE)	NOT NULL,
	NAME					VARCHAR2(50 BYTE)	NOT NULL,
	PASSWORD				VARCHAR2(50 BYTE)	NOT NULL,
	OFFICE_EMAIL				VARCHAR2(50 BYTE)	,
	PHONE_NO				VARCHAR2(20 BYTE)	,
	MEMBER_GRADE				INTEGER			DEFAULT 5		NOT NULL,
	ACTIVE					CHAR(1 BYTE)		DEFAULT 'Y'		NOT NULL,
	NOTICE					CHAR(1 BYTE)		DEFAULT 'N'		NOT NULL,
	REG_DATE				DATE			DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_MEMBER" PRIMARY KEY ("MEMBER_ID")
					
);

COMMENT ON TABLE GSI.TB_MEMBER					IS 'PWN PG 관리자 회원 ';
COMMENT ON COLUMN GSI.TB_MEMBER.IDX				IS 'IDX';
COMMENT ON COLUMN GSI.TB_MEMBER.MEMBER_ID			IS 'PWN 회원 아이디';
COMMENT ON COLUMN GSI.TB_MEMBER.NAME				IS '이름';
COMMENT ON COLUMN GSI.TB_MEMBER.PASSWORD			IS '비밀번호';
COMMENT ON COLUMN GSI.TB_MEMBER.OFFICE_EMAIL			IS '회사이메일';
COMMENT ON COLUMN GSI.TB_MEMBER.PHONE_NO			IS '전화번호';
COMMENT ON COLUMN GSI.TB_MEMBER.MEMBER_GRADE			IS '관리자등급(0:슈퍼관리자,1~5)';
COMMENT ON COLUMN GSI.TB_MEMBER.ACTIVE				IS 'Y:사용,N:중지';
COMMENT ON COLUMN GSI.TB_MEMBER.NOTICE				IS 'Y:사용,N:중지';
COMMENT ON COLUMN GSI.TB_MEMBER.REG_DATE			IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_MEMBER"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_MEMBER AS
SELECT IDX,MEMBER_ID,NAME,PASSWORD,OFFICE_EMAIL,PHONE_NO,MEMBER_GRADE,ACTIVE,NOTICE,REG_DATE
FROM GSI.TB_MEMBER;



------------------------------------------------------------------------
-- 18. 가맹점 관리 
------------------------------------------------------------------------
CREATE TABLE GSI.TB_MERCHANT
(
	IDX					NUMBER				NOT NULL,
	MERCHANT_ID				VARCHAR2(20 BYTE)	NOT NULL,
	NAME					VARCHAR2(100 BYTE)	NOT NULL,
	PASSWORD				VARCHAR2(50 BYTE)	,
	PW_UPDATE				CHAR(1 BYTE)		DEFAULT 'N' 	NOT NULL,
	BIZ_NATURE				VARCHAR2(50 BYTE)	,
	PRODUCT					VARCHAR2(100 BYTE)	,
	HOMEPAGE				VARCHAR2(50 BYTE)	,
	ADDR1					VARCHAR2(100 BYTE)	,
	ADDR2					VARCHAR2(200 BYTE)	,
	ZIPCODE					VARCHAR2(10 BYTE)	,
	TELNO					VARCHAR2(20 BYTE)	,	
	FAX					VARCHAR2(20 BYTE)	,
	EMAIL					VARCHAR2(100 BYTE)	,
	IDENTINO				VARCHAR2(20 BYTE)	,
	CEO_NAME				VARCHAR2(50 BYTE)	,
	CEO_ENG_NAME				VARCHAR2(50 BYTE)	,
	CEO_ADDR1				VARCHAR2(100 BYTE)	,
	CEO_ADDR2				VARCHAR2(100 BYTE)	,
	CEO_ZIPCODE				VARCHAR2(10 BYTE)	,
	CEO_TELNO				VARCHAR2(20 BYTE)	,
	CEO_PHONENO				VARCHAR2(20 BYTE)	,
	CEO_EMAIL				VARCHAR2(100 BYTE)	,
	CEO_IDENTINO				VARCHAR2(20 BYTE)	,
	SETTLE_PART_NAME			VARCHAR2(20 BYTE)	,
	SETTLE_PART_EMAIL			VARCHAR2(100 BYTE)	,
	SETTLE_PART_TELNO			VARCHAR2(20 BYTE)	,
	DEV_PART_NAME				VARCHAR2(20 BYTE)	,
	DEV_PART_EMAIL				VARCHAR2(100 BYTE)	,
	DEV_PART_TELNO				VARCHAR2(20 BYTE)	,
	SETTLE_BANK				VARCHAR2(100 BYTE)	,
	SETTLE_BANKCODE				VARCHAR2(10 BYTE)	,
	SETTLE_ACCOUNT				VARCHAR2(20 BYTE)	,
	SERVICE_DATE				DATE			,
	ACTIVE					CHAR(1 BYTE)		DEFAULT '0'		NOT NULL,
	COMMENT_IDX				NUMBER				,
	REG_DATE				DATE				DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_MERCHANT" PRIMARY KEY ("MERCHANT_ID")
					
);

COMMENT ON TABLE GSI.TB_MERCHANT				IS 'PWN PG 가맹점';
COMMENT ON COLUMN GSI.TB_MERCHANT.IDX				IS '인덱스';
COMMENT ON COLUMN GSI.TB_MERCHANT.MERCHANT_ID			IS '가맹점 아이디';
COMMENT ON COLUMN GSI.TB_MERCHANT.NAME				IS '회사명';
COMMENT ON COLUMN GSI.TB_MERCHANT.PASSWORD			IS '비밀번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.PW_UPDATE			IS '패스워드 업데이트여부 (Y,N)';
COMMENT ON COLUMN GSI.TB_MERCHANT.BIZ_NATURE			IS '사업자형태';
COMMENT ON COLUMN GSI.TB_MERCHANT.PRODUCT			IS '취급물품';
COMMENT ON COLUMN GSI.TB_MERCHANT.HOMEPAGE			IS '홈페이지';
COMMENT ON COLUMN GSI.TB_MERCHANT.ADDR1				IS '회사 주소1';
COMMENT ON COLUMN GSI.TB_MERCHANT.ADDR2				IS '회사 주소 2';
COMMENT ON COLUMN GSI.TB_MERCHANT.ZIPCODE			IS '회사 주소 우편번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.TELNO				IS '회사 대표 전화번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.FAX				IS '회사 대표 팩스번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.EMAIL				IS '회사 대표 이메일';
COMMENT ON COLUMN GSI.TB_MERCHANT.IDENTINO			IS '회사 식별번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.CEO_NAME			IS '그룹사 대표 이름';
COMMENT ON COLUMN GSI.TB_MERCHANT.CEO_ENG_NAME			IS '그룹사 대표 영문명';
COMMENT ON COLUMN GSI.TB_MERCHANT.CEO_ADDR1			IS '대표자 주소1';
COMMENT ON COLUMN GSI.TB_MERCHANT.CEO_ADDR2			IS '대표자 주소2';
COMMENT ON COLUMN GSI.TB_MERCHANT.CEO_ZIPCODE			IS '대표자 주소 우편번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.CEO_TELNO			IS '대표자 전화번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.CEO_PHONENO			IS '대표자 휴대폰번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.CEO_EMAIL			IS '대표자이메일';
COMMENT ON COLUMN GSI.TB_MERCHANT.CEO_IDENTINO			IS '대표자 식별번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.SETTLE_PART_NAME		IS '정산 담당자 이름';
COMMENT ON COLUMN GSI.TB_MERCHANT.SETTLE_PART_EMAIL		IS '정산 담당자 이메일';
COMMENT ON COLUMN GSI.TB_MERCHANT.SETTLE_PART_TELNO 		IS '정산 담당자 전화번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.DEV_PART_NAME			IS '개발 담당자 이름';
COMMENT ON COLUMN GSI.TB_MERCHANT.DEV_PART_EMAIL		IS '개발 담당자 이메일';
COMMENT ON COLUMN GSI.TB_MERCHANT.DEV_PART_TELNO		IS '개발 담당자 전화번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.SETTLE_BANK			IS '정산은행이름';
COMMENT ON COLUMN GSI.TB_MERCHANT.SETTLE_BANKCODE		IS '정산은행코드';
COMMENT ON COLUMN GSI.TB_MERCHANT.SETTLE_ACCOUNT		IS '정산 계좌번호';
COMMENT ON COLUMN GSI.TB_MERCHANT.ACTIVE			IS '0:예비 ,1:사용,2:중지,3:해지';
COMMENT ON COLUMN GSI.TB_MERCHANT.COMMENT_IDX			IS '변경기록관리인덱스';
COMMENT ON COLUMN GSI.TB_MERCHANT.REG_DATE			IS '등록일자 ';

CREATE SEQUENCE  "GSI"."SEQ_MERCHANT"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_MERCHANT AS
SELECT IDX,MERCHANT_ID,NAME,PASSWORD,PW_UPDATE,BIZ_NATURE,PRODUCT,HOMEPAGE,ADDR1,ADDR2,ZIPCODE,TELNO,FAX,EMAIL,IDENTINO,CEO_NAME,CEO_ENG_NAME,CEO_ADDR1,CEO_ADDR2,CEO_ZIPCODE,CEO_TELNO,CEO_PHONENO,CEO_EMAIL,CEO_IDENTINO,SETTLE_PART_NAME,SETTLE_PART_EMAIL,SETTLE_PART_TELNO,DEV_PART_NAME,DEV_PART_EMAIL,DEV_PART_TELNO,SETTLE_BANK,SETTLE_BANKCODE,SETTLE_ACCOUNT,SERVICE_DATE,ACTIVE,COMMENT_IDX,REG_DATE
FROM GSI.TB_MERCHANT;


------------------------------------------------------------------------
-- 19. 가맹점 거래관리  
------------------------------------------------------------------------

CREATE TABLE GSI.TB_MERCHANT_MNG
(
    IDX				NUMBER			NOT NULL,
    MERCHANT_ID			VARCHAR2(8 BYTE)	NOT NULL,
    CUR_TYPE			CHAR(3 BYTE)		,
    ONCE_LIMIT			NUMBER			NOT NULL,
    DAY_LIMIT			NUMBER			NOT NULL,
    MONTH_LIMIT			NUMBER			NOT NULL,
    CARD_MONTH_LIMIT		NUMBER			DEFAULT 0,
    TEMP_LIMIT			NUMBER			DEFAULT 0,
    DUPLICATION_COUNT		NUMBER			DEFAULT '10'        NOT NULL,
    REPORT_EMAIL		VARCHAR2(100 BYTE)	,
    DEMO			CHAR(1 BYTE)		DEFAULT 'N',
    VAN				VARCHAR2(10 BYTE)	DEFAULT 'DCP',
    VAN_ID				VARCHAR2(20 BYTE),
    VM_FEE					NUMBER				NOT NULL,
    JCB_FEE					NUMBER				NOT NULL,
    DEPOSIT			NUMBER				NOT NULL,
    TEMP			CHAR(1 BYTE)		,
    COMMENT_IDX                NUMBER			,    
    REG_DATE                DATE                DEFAULT SYSDATE    NOT NULL,
    CONSTRAINT "TB_MERCHANT_MNG" PRIMARY KEY ("MERCHANT_ID")
);

COMMENT ON TABLE GSI.TB_MERCHANT_MNG				IS 'PWN 가맹점 서비스 관리';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.IDX			IS '인덱스';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.MERCHANT_ID		IS '가맹점아이디';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.CUR_TYPE			IS '통화구분 JPY,USD,KRW';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.ONCE_LIMIT		IS '일회결제한도';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.DAY_LIMIT			IS '일일결제한도';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.MONTH_LIMIT		IS '월결제한도';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.CARD_MONTH_LIMIT		IS '1카드1가맹점1달 사용한도';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.TEMP_LIMIT		IS '없음.';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.DUPLICATION_COUNT		IS '1일 거래 횟수 제한 ';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.DEMO			IS 'DEMO 관리플래그 ';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.REPORT_EMAIL		IS '일일거래현황 이메일 전송 여부 이메일 주소 기입되면 전송';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.VAN			IS 'DCP 등의 VAN 사';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.VAN_ID			IS 'VAN 사 소속 아이디 ';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.VM_FEE			IS 'VM수수료정보 ';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.JCB_FEE			IS 'JCB수수료정보 ';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.DEPOSIT			IS '예치금 정보 ';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.COMMENT_IDX		IS 'SEQ_COMMNET_SERVICE';
COMMENT ON COLUMN GSI.TB_MERCHANT_MNG.REG_DATE			IS '등록일자 ';


CREATE SEQUENCE  "GSI"."SEQ_MERCHANT_MNG"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;



CREATE VIEW VW_MERCHANT_MNG AS
SELECT IDX, MERCHANT_ID, CUR_TYPE,   ONCE_LIMIT, DAY_LIMIT, MONTH_LIMIT,   CARD_MONTH_LIMIT, TEMP_LIMIT,DUPLICATION_COUNT,  REPORT_EMAIL, DEMO,VAN,VAN_ID, VM_FEE,JCB_FEE,DEPOSIT,TEMP, COMMENT_IDX, REG_DATE
FROM GSI.TB_MERCHANT_MNG;



------------------------------------------------------------------------
-- 20. 차지백 처리 
------------------------------------------------------------------------
CREATE TABLE GSI.TB_TRNSCTN_CB
(
  	IDX				  		NUMBER			NOT NULL,
  	TRANSACTION_ID   				VARCHAR2(12 BYTE)	NOT NULL,
	CB_STATE					CHAR(1 BYTE)		NOT NULL,
	ROOT_TRN_STATE					CHAR(2 BYTE)		NOT NULL,
	FLAG						CHAR(1 BYTE)		NOT NULL,
	COMMENT_IDX					NUMBER				,
	REG_DATE					DATE			DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT "TB_TRNSCTN_CB" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE GSI.TB_TRNSCTN_CB				IS '차지백거래관리';
COMMENT ON COLUMN GSI.TB_TRNSCTN_CB.IDX				IS '인덱스';
COMMENT ON COLUMN GSI.TB_TRNSCTN_CB.TRANSACTION_ID		IS 'PWN 거래번호';
COMMENT ON COLUMN GSI.TB_TRNSCTN_CB.CB_STATE			IS '1:등록2:처리중3:처리완료4. 반려';
COMMENT ON COLUMN GSI.TB_TRNSCTN_CB.ROOT_TRN_STATE		IS '원거래상태';
COMMENT ON COLUMN GSI.TB_TRNSCTN_CB.FLAG			IS '전송상태 (N,Y)';
COMMENT ON COLUMN GSI.TB_TRNSCTN_CB.COMMENT_IDX			IS '코멘트 인덱스';
COMMENT ON COLUMN GSI.TB_TRNSCTN_CB.REG_DATE			IS '등록 또는 접수일자 ';

CREATE SEQUENCE  "GSI"."SEQ_TRNSCTN_CB"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_TRNSCTN_CB AS
SELECT IDX,TRANSACTION_ID,CB_STATE,ROOT_TRN_STATE,FLAG,COMMENT_IDX,REG_DATE
FROM GSI.TB_TRNSCTN_CB;

------------------------------------------------------------------------
-- 21. 가맹점 MALL 관리
------------------------------------------------------------------------
CREATE TABLE GSI.TB_MERCHANT_MALL
(
	IDX          NUMBER                           NOT NULL,
  	MERCHANT_ID  VARCHAR2(20 BYTE)                NOT NULL,
 	MALL_ID      VARCHAR2(20 BYTE)                NOT NULL,
  	TEL          VARCHAR2(20 BYTE)                NOT NULL,
 	 FAX          VARCHAR2(20 BYTE)                NOT NULL,
  	EMAIL        VARCHAR2(100 BYTE)               NOT NULL,
  	SITE         VARCHAR2(100 BYTE)               NOT NULL,
  	ACTIVE       CHAR(1 BYTE)                     DEFAULT '1'                   NOT NULL,
  	REG_DATE     DATE                             DEFAULT SYSDATE               NOT NULL,
	CONSTRAINT "TB_MERCHANT_MALL" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE TB_MERCHANT_MALL IS 'GSI PG 몰관리';
COMMENT ON COLUMN TB_MERCHANT_MALL.IDX IS '인덱스';
COMMENT ON COLUMN TB_MERCHANT_MALL.MERCHANT_ID IS '가맹점아이디';
COMMENT ON COLUMN TB_MERCHANT_MALL.MALL_ID IS '아이디';
COMMENT ON COLUMN TB_MERCHANT_MALL.TEL IS '전화번호';
COMMENT ON COLUMN TB_MERCHANT_MALL.FAX IS '팩스번호';
COMMENT ON COLUMN TB_MERCHANT_MALL.EMAIL IS '이메일';
COMMENT ON COLUMN TB_MERCHANT_MALL.SITE IS 'WEBSITE';
COMMENT ON COLUMN TB_MERCHANT_MALL.ACTIVE IS '0:예비,1:사용,2:중지,3:해지';
COMMENT ON COLUMN TB_MERCHANT_MALL.REG_DATE IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_MERCHANT_MALL"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_MERCHANT_MALL AS
SELECT IDX, MERCHANT_ID, MALL_ID, TEL, FAX, EMAIL, SITE, ACTIVE, REG_DATE 
FROM GSI.TB_MERCHANT_MALL;



------------------------------------------------------------------------
-- 22. 정산 관리 - TRNSCTN
------------------------------------------------------------------------
CREATE TABLE GSI.TB_SETTLE_INFO
(
	IDX          			NUMBER                           NOT NULL,
	MERCHANT_ID  VARCHAR2(20 BYTE)   	NOT NULL,
	INVOICE_IDX  VARCHAR2(20 BYTE)		NOT NULL,
	SETTLE_IDX  	VARCHAR2(20BYTE) 		NOT NULL,
	SETTLE_TYPE	VARCHAR2(12BYTE)		NOT NULL,
  	START_DATE  VARCHAR2(10BYTE)		NOT NULL,
  	END_DATE 	 	VARCHAR2(10BYTE)		NOT NULL,
 	TOT_COUNT     		NUMBER					     	 NOT NULL,
 	AMOUNT			NUMBER							NOT NULL,
  	SETTLE_YN       CHAR(1 BYTE)                DEFAULT 'N'                   NOT NULL,
  	REG_DATE     DATE                             DEFAULT SYSDATE               NOT NULL,
	CONSTRAINT "TB_SETTLE_INFO" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE TB_SETTLE_INFO IS 'GSI PG 정산정보관리';
COMMENT ON COLUMN TB_SETTLE_INFO.IDX IS '인덱스';
COMMENT ON COLUMN TB_SETTLE_INFO.MERCHANT_ID IS '가맹점아이디';
COMMENT ON COLUMN TB_SETTLE_INFO.SETTLE_IDX IS '정산 인덱스';
COMMENT ON COLUMN TB_SETTLE_INFO.SETTLE_TYPE IS '정산 TYPE,T=TRANSACTION,C=CHARGEBACK,R=REFUND,F=FEE';
COMMENT ON COLUMN TB_SETTLE_INFO.START_DATE IS '정산 작성 시작일';
COMMENT ON COLUMN TB_SETTLE_INFO.END_DATE IS '정산 작성 종료일';
COMMENT ON COLUMN TB_SETTLE_INFO.TOT_COUNT IS '관련 건수';
COMMENT ON COLUMN TB_SETTLE_INFO.AMOUNT IS '합계금액';
COMMENT ON COLUMN TB_SETTLE_INFO.SETTLE_YN IS 'N=정산예정,Y=정산확정';
COMMENT ON COLUMN TB_SETTLE_INFO.REG_DATE IS '등록일';

CREATE SEQUENCE  "GSI"."SEQ_SETTLE_INFO"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_SETTLE_INFO AS
SELECT IDX, MERCHANT_ID,INVOICE_IDX,SETTLE_IDX,SETTLE_TYPE,START_DATE,END_DATE,TOT_COUNT,AMOUNT,SETTLE_YN, REG_DATE 
FROM GSI.TB_SETTLE_INFO;




------------------------------------------------------------------------
-- 23. 정산 INDEX 관리
------------------------------------------------------------------------
CREATE TABLE GSI.TB_SETTLE_IDX
(
	MERCHANT_ID  VARCHAR2(20 BYTE)   	NOT NULL,
	SETTLE_IDX  	VARCHAR2(20BYTE) 		NOT NULL,
	TRANSACTION_ID   VARCHAR2(12 BYTE)	NOT NULL
);

COMMENT ON TABLE TB_SETTLE_IDX IS 'GSI PG 정산정보관리';
COMMENT ON COLUMN TB_SETTLE_IDX.MERCHANT_ID IS '가맹점아이디';
COMMENT ON COLUMN TB_SETTLE_IDX.SETTLE_IDX IS '정산 인덱스';

CREATE SEQUENCE  "GSI"."SEQ_SETTLE_IDX"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_SETTLE_IDX AS
SELECT MERCHANT_ID, SETTLE_IDX,TRANSACTION_ID 
FROM GSI.TB_SETTLE_IDX;


------------------------------------------------------------------------
-- 24. 정산내역 및 INVOICE 관련 정보 
------------------------------------------------------------------------
CREATE TABLE GSI.TB_SETTLE
(
	IDX          			NUMBER                           NOT NULL,
	MERCHANT_ID  			VARCHAR2(20 BYTE)   	NOT NULL,
	INVOICE_IDX  				VARCHAR2(20BYTE) 		NOT NULL,
	TRNSCTN_IDX  			VARCHAR2(20BYTE) 		NOT NULL,
	CHARGEBACK_IDX  	VARCHAR2(20BYTE) 		NOT NULL,
	REFUND_IDX  				VARCHAR2(20BYTE) 		NOT NULL,
	FEE_IDX  						VARCHAR2(20BYTE) 		NOT NULL,
	DEPOSIT_IDX  			VARCHAR2(20BYTE) 		NOT NULL,
    FILE_NAME       			VARCHAR2(200 BYTE),
    SETTLE_YN       			CHAR(1 BYTE)                  DEFAULT 'N'                   NOT NULL,
	REG_DATE     				DATE                             DEFAULT SYSDATE               NOT NULL,
	CONSTRAINT "TB_SETTLE" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE TB_SETTLE IS 'GSI PG SETTLE 정보 INVOICE 관련 정보';
COMMENT ON COLUMN TB_SETTLE.MERCHANT_ID IS '가맹점아이디';
COMMENT ON COLUMN TB_SETTLE.INVOICE_IDX IS 'INVOICE 인덱스';
COMMENT ON COLUMN TB_SETTLE.TRNSCTN_IDX IS '거래 인덱스';
COMMENT ON COLUMN TB_SETTLE.CHARGEBACK_IDX IS '차지백 인덱스';
COMMENT ON COLUMN TB_SETTLE.REFUND_IDX IS '리펀드 인덱스';
COMMENT ON COLUMN TB_SETTLE.FEE_IDX IS '수수료 인덱스';
COMMENT ON COLUMN TB_SETTLE.DEPOSIT_IDX IS '예치금 인덱스';
COMMENT ON COLUMN TB_SETTLE.FILE_NAME IS '청구서 PDF 위치';
COMMENT ON COLUMN TB_SETTLE.SETTLE_YN IS '정산여부 Y,N';
COMMENT ON COLUMN TB_SETTLE.REG_DATE  IS '등록일 ';

CREATE SEQUENCE  "GSI"."SEQ_SETTLE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_SETTLE AS
SELECT IDX, MERCHANT_ID,INVOICE_IDX,TRNSCTN_IDX,CHARGEBACK_IDX,REFUND_IDX,FEE_IDX,DEPOSIT_IDX,FILE_NAME,SETTLE_YN,REG_DATE
FROM GSI.TB_SETTLE;

------------------------------------------------------------------------
-- 25. DEPOSIT 관련 정보 
------------------------------------------------------------------------
CREATE TABLE GSI.TB_DEPOSIT
(
	IDX          						NUMBER                         	NOT NULL,
	MERCHANT_ID  			VARCHAR2(20 BYTE)   	NOT NULL,
	CURRENT_RATE  		NUMBER	 						NOT NULL,
 	LAST_AMOUNT			NUMBER	 						NOT NULL,
 	CURR_AMOUNT 			NUMBER	 						NOT NULL,
 	TOTAL_AMOUNT			NUMBER	 						NOT NULL,
	REG_DATE     				DATE                             	DEFAULT SYSDATE               NOT NULL,
	CONSTRAINT "TB_DEPOSIT" PRIMARY KEY ("IDX")
);

COMMENT ON TABLE TB_DEPOSIT IS 'GSI DEPOSIT 정보';
COMMENT ON COLUMN TB_DEPOSIT.IDX IS '인덱스';
COMMENT ON COLUMN TB_DEPOSIT.MERCHANT_ID IS '가맹점아이디';
COMMENT ON COLUMN TB_DEPOSIT.CURRENT_RATE IS '현재 DEPOSIT';
COMMENT ON COLUMN TB_DEPOSIT.LAST_AMOUNT IS '지난달 DEPOSIT총액';
COMMENT ON COLUMN TB_DEPOSIT.CURR_AMOUNT IS '현재달 DEPOSIT 총액';
COMMENT ON COLUMN TB_DEPOSIT.TOTAL_AMOUNT IS '총 금액 ';
COMMENT ON COLUMN TB_DEPOSIT.REG_DATE  IS '등록일 ';

CREATE SEQUENCE  "GSI"."SEQ_DEPOSIT"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

CREATE VIEW VW_DEPOSIT AS
SELECT IDX, MERCHANT_ID,CURRENT_RATE,LAST_AMOUNT,CURR_AMOUNT,TOTAL_AMOUNT,REG_DATE
FROM GSI.TB_DEPOSIT;


INSERT INTO TB_MERCHANT ( IDX, MERCHANT_ID, NAME, PASSWORD, PW_UPDATE, BIZ_NATURE, PRODUCT,
HOMEPAGE, ADDR1, ADDR2, ZIPCODE, TELNO, FAX, EMAIL, IDENTINO, CEO_NAME, CEO_ENG_NAME, CEO_ADDR1,
CEO_ADDR2, CEO_ZIPCODE, CEO_TELNO, CEO_PHONENO, CEO_EMAIL, CEO_IDENTINO, SETTLE_PART_NAME,
SETTLE_PART_EMAIL, SETTLE_PART_TELNO, DEV_PART_NAME, DEV_PART_EMAIL, DEV_PART_TELNO, SETTLE_BANK,
SETTLE_BANKCODE, SETTLE_ACCOUNT, SERVICE_DATE, ACTIVE, COMMENT_IDX,
REG_DATE ) VALUES ( 
SEQ_MERCHANT.NEXTVAL, 'panworld', 'PanWorld-Net', 'ARyUXzDOLLr8RS85hA8CVpMznEI=', 'Y', '1111', '1111'
, '1111', '1111', '1111', '1111', '1111', '1111', 'phing@ktt-korea.com', '1111', '1111'
, '1111', '1111', '1111', '1111', '1111', '1111', 'phing@ktt-korea.com', '1111', '1111'
, 'phing@ktt-korea.com', '1111', '1111', 'phing@ktt-korea.com', '1111', '1111', '1111'
, '1111',  TO_Date( '01/21/2009 11:56:15 오전', 'MM/DD/YYYY HH:MI:SS AM'), '1', 0
,  TO_Date( '01/21/2009 11:56:15 오전', 'MM/DD/YYYY HH:MI:SS AM')); 
commit;
 
INSERT INTO TB_CODE
(   
    SELECT 
SEQ_CODE.NEXTVAL, ALIAS, ACODE, 
   CODE, KR_VALUE, JP_VALUE, 
   EN_VALUE, MEMBER_ID, ACTIVE, 
   REG_DATE
FROM KTT.PG_CODE
);

